# Generated by Django 4.2.7 on 2025-08-16 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Format: 20xx-xxxxxx', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must be in format 20xx-xxxxxx (e.g., 2023-123456)', regex='^20\\d{2}-\\d{6}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pe_course', models.CharField(choices=[('PEDUONE', 'PEDU ONE'), ('PEDUTWO', 'PEDU TWO'), ('PEDUTRI', 'PEDU TRI'), ('PEDUFOR', 'PEDU FOR'), ('N/A', 'Not Enrolled in PE')], default='N/A', max_length=10)),
                ('block_section', models.CharField(help_text='Block/Section (no spaces allowed, e.g., STEM241, CS231)', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gym_students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GymSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_sessions', to='gym_app.student')),
            ],
            options={
                'db_table': 'gym_sessions',
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['student', 'date'], name='gym_session_student_17daf1_idx'), models.Index(fields=['is_active'], name='gym_session_is_acti_0a1bad_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyGymStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='gym_app.student')),
            ],
            options={
                'db_table': 'gym_daily_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', 'date'], name='gym_daily_s_student_87dbf1_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
