# Generated by Django 4.2.7 on 2025-08-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_remove_auto_now_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rfid',
            field=models.CharField(blank=True, help_text='RFID tag identifier for gym access', max_length=50, null=True),
        ),
    ]
