# Generated by Django 4.2.7 on 2025-08-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_populate_rfid_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rfid',
            field=models.CharField(blank=True, help_text='RFID tag identifier for gym access', max_length=50, null=True, unique=True),
        ),
    ]
