# Generated by Django 4.2.7 on 2025-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_add_rfid_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('block_section', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'gym_feedbacks',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['email'], name='gym_feedbac_email_39017d_idx'), models.Index(fields=['submitted_at'], name='gym_feedbac_submitt_461348_idx')],
            },
        ),
    ]
